project:
  type: website

website:
  title: "Métricas de MetaDocencia"
  sidebar:  
    contents:
      - href: tablero-correo.qmd
        text: Mailchimp
      - href: tablero-zenodo.qmd
        text: Zenodo

format:
  html:
    theme: [flatly, style/metadocencia.scss]
    toc: true



