project:
  type: website

website:
  title: "Métricas de Mailchimp"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre MetaDocencia
      - href: dashboard.qmd
        text: Tablero

format:
  html:
    theme: [flatly, style/metadocencia.scss]
    toc: true



